[package]
name = "formula"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
config = { version= "0.13.1", features = ["json5"] }
serde = { version = "1.0.139", features = ["derive"] }
eyre = "0.6.8"
color-eyre = "0.6.2"
tracing = "0.1.35"
tracing-log = { version = "0.1.3", features = ["env_logger"] }
tracing-subscriber = "0.3.14"
tracing-futures = "0.2.5"